import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState } from "react";
import { LogOut, RefreshCw } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { listAdminRewards, updateAdminReward } from "@/lib/fun-cosmos-submissions.functions";
import { Button } from "@/components/ui/button";
import "@/living.css";

export const Route = createFileRoute("/admin/fun-cosmos/rewards")({ head: () => ({ meta: [{ title: "Phần thưởng | FUN COSMOS Admin" }, { name: "description", content: "Quản lý phần thưởng FUN COSMOS." }, { property: "og:title", content: "Phần thưởng | FUN COSMOS Admin" }, { property: "og:description", content: "Khu vực quản trị phần thưởng." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: AdminRewards });
function AdminRewards() {
  const navigate = useNavigate(); const list = useServerFn(listAdminRewards); const update = useServerFn(updateAdminReward); const [rows, setRows] = useState<any[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(true);
  async function load() { setBusy(true); setError(""); try { const { data: user } = await supabase.auth.getUser(); if (!user.user) { await navigate({ to: "/admin/login" }); return; } setRows(await list()); } catch { setError("Bạn không có quyền quản trị hoặc phiên đăng nhập đã hết hạn."); } finally { setBusy(false); } } useEffect(() => { void load(); }, []);
  return <main className="fc-admin-page"><header><div><p className="lc-eyebrow">✧ FUN COSMOS ADMIN</p><h1>PHẦN THƯỞNG</h1></div><nav><a href="/admin/fun-cosmos/submissions">Bài tham gia</a><Button variant="outline" onClick={async () => { await supabase.auth.signOut(); await navigate({ to: "/admin/login" }); }}><LogOut /> Đăng xuất</Button></nav></header><Button variant="outline" onClick={() => void load()}><RefreshCw /> Làm mới</Button>{error && <p role="alert" className="fc-form-error">{error}</p>}<div className="fc-admin-list" aria-busy={busy}>{rows.map((row) => { const submission = Array.isArray(row.fun_cosmos_submissions) ? row.fun_cosmos_submissions[0] : row.fun_cosmos_submissions; return <article key={row.id}><header><div><strong>{submission?.public_submission_code}</strong><h2>{submission?.display_name}</h2></div><span>{row.status}</span></header><dl><div><dt>Phần thưởng</dt><dd>{row.reward_amount.toLocaleString("vi-VN")} {row.token_symbol}</dd></div><div><dt>Ví</dt><dd>{row.wallet_address}</dd></div><div><dt>TX Hash</dt><dd>{row.tx_hash || "Chưa có"}</dd></div></dl>{submission?.duplicate_flag && <p className="fc-duplicate">Bài đang có cờ kiểm tra trùng.</p>}<div className="fc-admin-actions"><select defaultValue={row.status} id={`reward-${row.id}`} aria-label={`Trạng thái thưởng ${submission?.public_submission_code}`}><option value="approved">Đã duyệt</option><option value="processing">Đang xử lý</option><option value="sent">Đã gửi</option><option value="failed">Thất bại</option></select><input id={`tx-${row.id}`} defaultValue={row.tx_hash ?? ""} placeholder="TX Hash thật (bắt buộc khi đã gửi)" /><input id={`reward-note-${row.id}`} defaultValue={row.notes ?? ""} placeholder="Ghi chú nội bộ" /><Button onClick={async () => { const statusEl = document.getElementById(`reward-${row.id}`) as HTMLSelectElement | null; const txEl = document.getElementById(`tx-${row.id}`) as HTMLInputElement | null; const noteEl = document.getElementById(`reward-note-${row.id}`) as HTMLInputElement | null; if (!statusEl) return; try { await update({ data: { id: row.id, status: statusEl.value as "approved"|"processing"|"sent"|"failed", txHash: txEl?.value ?? "", note: noteEl?.value ?? "" } }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể cập nhật."); } }}>Cập nhật</Button></div></article>; })}</div></main>;
}