import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState } from "react";
import { LogOut, RefreshCw, Search } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { listAdminSubmissions, updateAdminSubmission } from "@/lib/fun-cosmos-submissions.functions";
import { Button } from "@/components/ui/button";
import "@/living.css";

export const Route = createFileRoute("/admin/fun-cosmos/submissions")({
  head: () => ({ meta: [{ title: "Bài tham gia | FUN COSMOS Admin" }, { name: "description", content: "Quản lý bài tham gia FUN COSMOS." }, { property: "og:title", content: "Bài tham gia | FUN COSMOS Admin" }, { property: "og:description", content: "Khu vực quản trị bài tham gia." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: AdminSubmissions,
});

function AdminSubmissions() {
  const navigate = useNavigate(); const list = useServerFn(listAdminSubmissions); const update = useServerFn(updateAdminSubmission); const [rows, setRows] = useState<any[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(true);
  async function load() { setBusy(true); setError(""); try { const { data: user } = await supabase.auth.getUser(); if (!user.user) { await navigate({ to: "/admin/login" }); return; } setRows(await list({ data: { search, status } })); } catch { setError("Bạn không có quyền quản trị hoặc phiên đăng nhập đã hết hạn."); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  return <main className="fc-admin-page"><header><div><p className="lc-eyebrow">✧ FUN COSMOS ADMIN</p><h1>BÀI THAM GIA</h1></div><nav><a href="/admin/fun-cosmos/rewards">Phần thưởng</a><Button variant="outline" onClick={async () => { await supabase.auth.signOut(); await navigate({ to: "/admin/login" }); }}><LogOut /> Đăng xuất</Button></nav></header><form className="fc-admin-filters" onSubmit={(e) => { e.preventDefault(); void load(); }}><label>Tìm kiếm<input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Mã bài, tên, email hoặc ví" /></label><label>Trạng thái<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Tất cả</option><option value="submitted">Đã gửi</option><option value="under_review">Đang xem xét</option><option value="needs_revision">Cần bổ sung</option><option value="approved">Đã duyệt</option><option value="rejected">Từ chối</option></select></label><Button><Search /> Lọc</Button><Button type="button" variant="outline" onClick={() => void load()}><RefreshCw /> Làm mới</Button></form>{error && <p role="alert" className="fc-form-error">{error}</p>}<div className="fc-admin-list" aria-busy={busy}>{rows.map((row) => <article key={row.id}><header><div><strong>{row.public_submission_code}</strong><h2>{row.display_name}</h2></div><span>{row.status}</span></header><dl><div><dt>Email</dt><dd>{row.email}</dd></div><div><dt>Telegram</dt><dd>{row.telegram}</dd></div><div><dt>Ví CAMLY</dt><dd>{row.wallet_address}</dd></div><div><dt>Ngày gửi</dt><dd>{new Date(row.submitted_at).toLocaleString("vi-VN")}</dd></div></dl>{row.duplicate_flag && <p className="fc-duplicate">Cần kiểm tra trùng: {row.duplicate_reasons.join(", ")}</p>}<details><summary>Xem 7 nội dung</summary>{[row.character,row.dream,row.gameplay,row.angel_ai_support,row.desired_reward_or_progress,row.world_change,row.real_world_connection].map((answer, i) => <p key={i}><b>{i + 1}.</b> {answer}</p>)}</details><div className="fc-admin-actions"><select defaultValue={row.status} aria-label={`Trạng thái ${row.public_submission_code}`} id={`status-${row.id}`}><option value="under_review">Đang xem xét</option><option value="needs_revision">Cần bổ sung</option><option value="approved">Duyệt</option><option value="rejected">Từ chối</option></select><input id={`note-${row.id}`} placeholder="Ghi chú / thông báo cho người tham gia" /><Button onClick={async () => { const statusEl = document.getElementById(`status-${row.id}`) as HTMLSelectElement | null; const noteEl = document.getElementById(`note-${row.id}`) as HTMLInputElement | null; if (!statusEl) return; await update({ data: { id: row.id, status: statusEl.value as "under_review"|"needs_revision"|"approved"|"rejected", note: noteEl?.value ?? "" } }); await load(); }}>Cập nhật</Button></div></article>)}</div></main>;
}