export const descriptions: Record<number, string> = {
  1: "Sách Urantia mở ra bức tranh vũ trụ và hành trình học hỏi.",
  2: "Khám phá vũ trụ cùng Sách Urantia tiếng Việt.",
  3: "Vũ trụ là một trường học vĩ đại: học hỏi, trải nghiệm và trưởng thành.",
  4: "Bảy thế giới dinh thự, mỗi thế giới là một bước tiến hóa.",
  5: "Một hành trình hướng về sự hoàn thiện.",
  6: "FUN COSMOS — Hành trình trở về, từ khai thị đến trải nghiệm.",
  7: "FUN COSMOS: khám phá, học hỏi, sáng tạo và cùng kiến tạo tương lai.",
  8: "Nhập vai, mô phỏng cuộc sống, cộng đồng, sáng tạo, Angel AI và O2O.",
  9: "Từ thiết kế và chợ sáng tạo đến những công trình ngoài đời thật.",
  10: "Bảy thế giới trải nghiệm kết nối trò chơi và cuộc sống.",
  11: "Người chơi khám phá, sáng tạo, kết nối, phát triển và hiện thực hóa.",
  12: "Câu chuyện Anna: từ khu vườn trong game đến trồng cây ngoài đời thật.",
  13: "Vòng lặp: ước mơ, mô phỏng, học hỏi, sáng tạo, hành động, xác minh, ghi nhận, tiến hóa.",
  14: "Trải nghiệm phiên bản tốt hơn của chính mình và cùng xây dựng thế giới tốt đẹp hơn.",
  15: "Năm trụ cột FUN COSMOS với Angel AI và PureLove Protocol.",
  16: "Angel AI: người hướng dẫn, bạn đồng hành, người thầy và trợ lý sáng tạo.",
  17: "Angel AI đồng hành và cá nhân hóa hành trình của người chơi.",
  18: "Love Score: hành động, bằng chứng, xác minh và ghi nhận đóng góp.",
  19: "Những đóng góp tích cực được ghi nhận; Love Score không đánh giá giá trị con người.",
  20: "Trồng cây trong game, tham gia Green Earth và giúp thế giới phát triển.",
  21: "Bạn sẽ sáng tạo câu chuyện, nhân vật, thế giới, âm nhạc, AI, game hay cộng đồng?",
  23: "O2O kết nối hai chiều giữa thế giới số và cuộc sống thật.",
  24: "FUN COSMOS kết nối toàn bộ hệ sinh thái FUN.",
  25: "Niềm vui khám phá, học hỏi, sáng tạo và kết nối trong FUN COSMOS.",
  26: "Năm câu hỏi để cùng nhau xây dựng FUN COSMOS.",
  27: "Thực hành phác thảo trải nghiệm FUN COSMOS của bạn qua bảy bước.",
};
