export const descriptions: Record<number, string> = {
  1: "Sách Urantia mở ra bức tranh vũ trụ và hành trình học hỏi.",
  2: "Khám phá vũ trụ cùng Sách Urantia tiếng Việt.",
  3: "Vũ trụ là một trường học vĩ đại: học hỏi, trải nghiệm và trưởng thành.",
  4: "Bảy thế giới dinh thự, mỗi thế giới là một bước tiến hóa.",
  5: "Một hành trình hướng về sự hoàn thiện.",
  6: "FUN COSMOS — Hành trình trở về, từ khai thị đến trải nghiệm.",
  7: "FUN COSMOS: khám phá, học hỏi, sáng tạo và cùng kiến tạo tương lai.",
  8: "Nhập vai, mô phỏng cuộc sống, cộng đồng, sáng tạo, Angel AI và O2O.",
  9: "Từ thiết kế và chợ sáng tạo đến những công trình ngoài đời thật.",
  10: "Bảy thế giới trải nghiệm kết nối trò chơi và cuộc sống.",
  11: "Người chơi khám phá, sáng tạo, kết nối, phát triển và hiện thực hóa.",
  12: "Câu chuyện Anna: từ khu vườn trong game đến trồng cây ngoài đời thật.",
  13: "Vòng lặp: ước mơ, mô phỏng, học hỏi, sáng tạo, hành động, xác minh, ghi nhận, tiến hóa.",
  14: "Trải nghiệm phiên bản tốt hơn của chính mình và cùng xây dựng thế giới tốt đẹp hơn.",
  15: "Năm trụ cột FUN COSMOS với Angel AI và PureLove Protocol.",
  16: "Angel AI: người hướng dẫn, bạn đồng hành, người thầy và trợ lý sáng tạo.",
  17: "Angel AI đồng hành và cá nhân hóa hành trình của người chơi.",
  18: "Love Score: hành động, bằng chứng, xác minh và ghi nhận đóng góp.",
  19: "Những đóng góp tích cực được ghi nhận; Love Score không đánh giá giá trị con người.",
  20: "Trồng cây trong game, tham gia Green Earth và giúp thế giới phát triển.",
  21: "Bạn sẽ sáng tạo câu chuyện, nhân vật, thế giới, âm nhạc, AI, game hay cộng đồng?",
  23: "O2O kết nối hai chiều giữa thế giới số và cuộc sống thật.",
  24: "FUN COSMOS kết nối toàn bộ hệ sinh thái FUN.",
  25: "Niềm vui khám phá, học hỏi, sáng tạo và kết nối trong FUN COSMOS.",
  26: "Năm câu hỏi để cùng nhau xây dựng FUN COSMOS.",
  27: "Thực hành phác thảo trải nghiệm FUN COSMOS của bạn qua bảy bước.",
};

export const descriptionsEn: Record<number, string> = {
  1: "The Urantia Book opens a view of the cosmos and a journey of learning.",
  2: "Explore the cosmos with the Vietnamese edition of The Urantia Book.",
  3: "The universe is a great school for learning, experience and growth.",
  4: "Seven mansion worlds, each representing a step of growth.",
  5: "A journey toward becoming more complete.",
  6: "FUN COSMOS — a journey from inspiration to experience.",
  7: "Explore, learn, create and build the future together in FUN COSMOS.",
  8: "Role-play, life simulation, community, creation, Angel AI and O2O.",
  9: "From design and creative markets to real-world projects.",
  10: "Seven experience worlds connect play and life.",
  11: "Players explore, create, connect, grow and bring ideas to life.",
  12: "Anna's story: from a garden in the game to planting in real life.",
  13: "The loop: dream, simulate, learn, create, act, verify, recognize and evolve.",
  14: "Explore a better version of yourself and help build a better world.",
  15: "The five FUN COSMOS pillars with Angel AI and PureLove Protocol.",
  16: "Angel AI as guide, companion, teacher and creative assistant.",
  17: "Angel AI accompanies players and personalizes their journeys.",
  18: "Love Score: action, evidence, verification and recognition.",
  19: "Positive contributions are recognized; Love Score does not judge human worth.",
  20: "Plant in the game, join Green Earth and help the world grow.",
  21: "Will you create a story, character, world, music, AI, game or community?",
  23: "O2O connects digital worlds and real life in both directions.",
  24: "FUN COSMOS connects the FUN ecosystem.",
  25: "The joy of exploring, learning, creating and connecting in FUN COSMOS.",
  26: "Five questions to help build FUN COSMOS together.",
  27: "Sketch your own FUN COSMOS experience in seven steps.",
};
