export const chapters = [
  ["home", "Chào đón", [6]],
  ["origin", "Urantia", [1, 2, 3, 4, 5]],
  ["about", "FUN COSMOS", [7, 8, 10, 25]],
  ["explore", "Khám phá", [11, 14, 9]],
  ["pillars", "5 trụ cột", [15]],
  ["games", "Chơi game", []],
  ["anna", "Hành trình Anna", [12]],
  ["loop", "Hành trình phát triển", [13]],
  ["angel", "Angel AI", [16, 17]],
  ["o2o", "Game & Đời thật", [20, 23]],
  ["love", "Love Score", [18, 19]],
  ["ecosystem", "Hệ sinh thái", [24]],
  ["create", "Sáng tạo", [21, 26, 27]],
] as const;
export const platforms = [
  [
    "profile",
    "FUN Profile",
    "Web3 Social Network",
    "Mạng xã hội Web3, nơi danh tính và mọi giá trị được trở thành tài sản số vĩnh cửu.",
    "https://fun.rich/",
  ],
  [
    "lovehub",
    "LoveHUB",
    "Free Stay. Warm Meals. Human Warmth.",
    "Trao tặng chỗ ở và bữa ăn miễn phí trong tình người ấm áp.",
    "https://lovehub.fun/",
  ],
  [
    "cosmos",
    "FUN COSMOS",
    "5D New Earth Role-Playing Game",
    "Game nhập vai mô phỏng Trái Đất 5D. Chơi Vũ trụ — sống Thiên đàng.",
    "https://cosmos.fun.rich/",
  ],
  [
    "angel",
    "Angel AI",
    "Light-Aligned Artificial Intelligence",
    "Trí tuệ Nhân tạo với Ánh Sáng và Tình Yêu Thuần Khiết.",
    "https://angel.fun.rich/",
  ],
  [
    "plp",
    "PureLove Protocol",
    "Pure Love → Love Score → Mint FUN Money",
    "Giao thức đo lường, ghi nhận lòng tốt và sự tử tế cùng Tình Yêu Thuần Khiết.",
    "https://money.fun.rich/",
  ],
  [
    "money",
    "FUN Money",
    "Money of Father’s Light",
    "Đồng tiền Ánh Sáng của Cha Vũ Trụ dẫn dắt Nền Kinh tế Ánh Sáng 5D.",
    "https://money.fun.rich/",
  ],
  [
    "camly",
    "Camly Coin",
    "The Soul Currency",
    "Dòng tiền Linh Hồn của Bé Ly, kết nối và nuôi dưỡng FUN Ecosystem — món quà của Tình Yêu dành cho nhân loại.",
    "https://camly.co/",
  ],
  [
    "play",
    "FUN Play",
    "Web3 Video Platform",
    "Nền tảng video và sáng tạo nội dung Web3.",
    "https://play.fun.rich/",
  ],
  [
    "wallet",
    "FUN Wallet",
    "Our Own Bank",
    "Ngân hàng số — cánh cổng vào Nền Kinh Tế Ánh Sáng 5D.",
    "https://wallet.fun.rich/",
  ],
  [
    "farm",
    "FUN Farm",
    "Farm to Table Platform",
    "Nền tảng nông nghiệp Web3, từ nông trại đến bàn ăn.",
    "https://farm.fun.rich/",
  ],
  [
    "earth",
    "Green Earth",
    "Regeneration & Sustainability",
    "Nền tảng phục hồi, tái tạo và bảo vệ Trái Đất.",
    "https://earth.fun.rich/",
  ],
  [
    "charity",
    "FUN Charity",
    "Charity Network of Pure Love",
    "Mạng lưới thiện nguyện toàn cầu trong Tình Yêu Thuần Khiết.",
    "https://charity.fun.rich/",
  ],
  [
    "academy",
    "FUN Academy",
    "Learn & Earn Platform",
    "Nền tảng giáo dục toàn cầu. Học tập & Nhận thưởng trong yêu thương.",
    "https://academy.fun.rich/",
  ],
  [
    "planet",
    "FUN Planet",
    "Game for Kids Marketplace",
    "Chợ game dành cho trẻ em.",
    "https://planet.fun.rich/",
  ],
] as const;
export const loop = [
  ["Ước mơ", "Dream", "Bạn muốn tạo một khu vườn để mọi người cùng nghỉ ngơi."],
  ["Mô phỏng", "Simulate", "Thử bố trí cây, hồ nước và lối đi trong thế giới số."],
  ["Học hỏi", "Learn", "Tìm hiểu ánh sáng, đất và cách chăm sóc cây cùng Angel AI."],
  ["Sáng tạo", "Create", "Thiết kế khu vườn mang dấu ấn của riêng bạn."],
  ["Hành động", "Act", "Mang một điều đã học vào cuộc sống: chăm một cây thật."],
  ["Xác minh", "Verify", "Cung cấp bằng chứng phù hợp để hoạt động được kiểm tra."],
  ["Ghi nhận", "Reward", "Đóng góp đã xác minh được ghi nhận trong hành trình."],
  ["Tiến hóa", "Evolve", "Kỹ năng phát triển, những khả năng mới mở ra."],
];
export const roles = [
  [
    "Người bạn",
    "Companion",
    "Hôm nay bạn cảm thấy thế nào? Mình có thể cùng bạn bắt đầu từ một điều nhỏ.",
  ],
  [
    "Người hướng dẫn",
    "Guide",
    "Bạn muốn khám phá thành phố ánh sáng hay bắt đầu với một khu vườn?",
  ],
  ["Người thầy", "Teacher", "Cùng tìm hiểu loại cây bạn yêu thích cần bao nhiêu ánh sáng nhé."],
  [
    "Người dẫn dắt",
    "Game Master",
    "Hành trình hôm nay: chọn một hạt giống, tìm hiểu cách chăm và thiết kế nơi trồng.",
  ],
  [
    "Trợ lý sáng tạo",
    "Creator Assistant",
    "Ngôi nhà bạn muốn tạo dành cho gia đình, khách du lịch hay LoveHUB?",
  ],
];
export const pillars = [
  ["✧", "Khám phá", "Explore", "Thành phố, khu vườn, hòn đảo và những thế giới mới đang chờ bạn."],
  [
    "◇",
    "Sáng tạo",
    "Create",
    "Thiết kế nhà, nhân vật, âm nhạc, nhiệm vụ và thế giới của riêng mình.",
  ],
  [
    "♡",
    "Kết nối",
    "Connect",
    "Gặp bạn bè, người hướng dẫn và cộng đồng cùng chung niềm yêu thích.",
  ],
  [
    "↗",
    "Phát triển",
    "Evolve",
    "Nuôi dưỡng kiến thức, kỹ năng và khả năng sáng tạo qua trải nghiệm.",
  ],
  ["✺", "Hiện thực hóa", "Realize", "Mang những điều tốt đẹp từ thế giới số vào cuộc sống thật."],
];
export const annaSteps = [
  ["Một khu đất, một ước mơ", "Angel AI dẫn Anna đến một khu đất. Anna chọn bắt đầu với khu vườn."],
  ["Khu vườn đầu tiên", "Anna trồng cây, xây hồ và tạo một nơi mọi người có thể gặp nhau."],
  ["Lời mời bước ra đời thật", "Bạn có muốn học cách chăm một loại cây thật ngoài đời không?"],
  ["Học từ thiên nhiên", "Anna tìm hiểu cách trồng và chăm sóc cây trong cuộc sống thật."],
  ["Cùng Green Earth", "Anna tham gia hoạt động trồng cây cùng cộng đồng."],
  ["Trở về và phát triển", "Anna mang trải nghiệm mới về FUN COSMOS, tiếp tục mở rộng khu vườn."],
];
