/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AngelAiRouteImport } from './routes/angel-ai'
import { Route as CosmosRouteImport } from './routes/cosmos'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as EmailVerifiedRouteImport } from './routes/email-verified'
import { Route as LoveScoreRouteImport } from './routes/love-score'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TaiKhoanRouteImport } from './routes/tai-khoan'
import { Route as TaoYTuongRouteImport } from './routes/tao-y-tuong'
import { Route as YourTurnRouteImport } from './routes/your-turn'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as FunCosmosTraCuuRouteImport } from './routes/fun-cosmos.tra-cuu'
import { Route as AdminFunCosmosRewardsRouteImport } from './routes/admin.fun-cosmos.rewards'
import { Route as AdminFunCosmosSubmissionsRouteImport } from './routes/admin.fun-cosmos.submissions'
import { Route as ApiPublicResetPasswordRouteImport } from './routes/api/public/reset-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AngelAiRoute = AngelAiRouteImport.update({
  id: '/angel-ai',
  path: '/angel-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmosRoute = CosmosRouteImport.update({
  id: '/cosmos',
  path: '/cosmos',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifiedRoute = EmailVerifiedRouteImport.update({
  id: '/email-verified',
  path: '/email-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const LoveScoreRoute = LoveScoreRouteImport.update({
  id: '/love-score',
  path: '/love-score',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiKhoanRoute = TaiKhoanRouteImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => rootRouteImport,
} as any)
const TaoYTuongRoute = TaoYTuongRouteImport.update({
  id: '/tao-y-tuong',
  path: '/tao-y-tuong',
  getParentRoute: () => rootRouteImport,
} as any)
const YourTurnRoute = YourTurnRouteImport.update({
  id: '/your-turn',
  path: '/your-turn',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FunCosmosTraCuuRoute = FunCosmosTraCuuRouteImport.update({
  id: '/fun-cosmos/tra-cuu',
  path: '/fun-cosmos/tra-cuu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFunCosmosRewardsRoute = AdminFunCosmosRewardsRouteImport.update({
  id: '/admin/fun-cosmos/rewards',
  path: '/admin/fun-cosmos/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFunCosmosSubmissionsRoute =
  AdminFunCosmosSubmissionsRouteImport.update({
    id: '/admin/fun-cosmos/submissions',
    path: '/admin/fun-cosmos/submissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicResetPasswordRoute = ApiPublicResetPasswordRouteImport.update({
  id: '/api/public/reset-password',
  path: '/api/public/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/angel-ai': typeof AngelAiRoute
  '/cosmos': typeof CosmosRoute
  '/ecosystem': typeof EcosystemRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/love-score': typeof LoveScoreRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tao-y-tuong': typeof TaoYTuongRoute
  '/your-turn': typeof YourTurnRoute
  '/admin/login': typeof AdminLoginRoute
  '/fun-cosmos/tra-cuu': typeof FunCosmosTraCuuRoute
  '/admin/fun-cosmos/rewards': typeof AdminFunCosmosRewardsRoute
  '/admin/fun-cosmos/submissions': typeof AdminFunCosmosSubmissionsRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/angel-ai': typeof AngelAiRoute
  '/cosmos': typeof CosmosRoute
  '/ecosystem': typeof EcosystemRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/love-score': typeof LoveScoreRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tao-y-tuong': typeof TaoYTuongRoute
  '/your-turn': typeof YourTurnRoute
  '/admin/login': typeof AdminLoginRoute
  '/fun-cosmos/tra-cuu': typeof FunCosmosTraCuuRoute
  '/admin/fun-cosmos/rewards': typeof AdminFunCosmosRewardsRoute
  '/admin/fun-cosmos/submissions': typeof AdminFunCosmosSubmissionsRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/angel-ai': typeof AngelAiRoute
  '/cosmos': typeof CosmosRoute
  '/ecosystem': typeof EcosystemRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/love-score': typeof LoveScoreRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tao-y-tuong': typeof TaoYTuongRoute
  '/your-turn': typeof YourTurnRoute
  '/admin/login': typeof AdminLoginRoute
  '/fun-cosmos/tra-cuu': typeof FunCosmosTraCuuRoute
  '/admin/fun-cosmos/rewards': typeof AdminFunCosmosRewardsRoute
  '/admin/fun-cosmos/submissions': typeof AdminFunCosmosSubmissionsRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/angel-ai'
    | '/cosmos'
    | '/ecosystem'
    | '/email-verified'
    | '/love-score'
    | '/reset-password'
    | '/tai-khoan'
    | '/tao-y-tuong'
    | '/your-turn'
    | '/admin/login'
    | '/fun-cosmos/tra-cuu'
    | '/admin/fun-cosmos/rewards'
    | '/admin/fun-cosmos/submissions'
    | '/api/public/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/angel-ai'
    | '/cosmos'
    | '/ecosystem'
    | '/email-verified'
    | '/love-score'
    | '/reset-password'
    | '/tai-khoan'
    | '/tao-y-tuong'
    | '/your-turn'
    | '/admin/login'
    | '/fun-cosmos/tra-cuu'
    | '/admin/fun-cosmos/rewards'
    | '/admin/fun-cosmos/submissions'
    | '/api/public/reset-password'
  id:
    | '__root__'
    | '/'
    | '/angel-ai'
    | '/cosmos'
    | '/ecosystem'
    | '/email-verified'
    | '/love-score'
    | '/reset-password'
    | '/tai-khoan'
    | '/tao-y-tuong'
    | '/your-turn'
    | '/admin/login'
    | '/fun-cosmos/tra-cuu'
    | '/admin/fun-cosmos/rewards'
    | '/admin/fun-cosmos/submissions'
    | '/api/public/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AngelAiRoute: typeof AngelAiRoute
  CosmosRoute: typeof CosmosRoute
  EcosystemRoute: typeof EcosystemRoute
  EmailVerifiedRoute: typeof EmailVerifiedRoute
  LoveScoreRoute: typeof LoveScoreRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TaiKhoanRoute: typeof TaiKhoanRoute
  TaoYTuongRoute: typeof TaoYTuongRoute
  YourTurnRoute: typeof YourTurnRoute
  AdminLoginRoute: typeof AdminLoginRoute
  FunCosmosTraCuuRoute: typeof FunCosmosTraCuuRoute
  AdminFunCosmosRewardsRoute: typeof AdminFunCosmosRewardsRoute
  AdminFunCosmosSubmissionsRoute: typeof AdminFunCosmosSubmissionsRoute
  ApiPublicResetPasswordRoute: typeof ApiPublicResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angel-ai': {
      id: '/angel-ai'
      path: '/angel-ai'
      fullPath: '/angel-ai'
      preLoaderRoute: typeof AngelAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmos': {
      id: '/cosmos'
      path: '/cosmos'
      fullPath: '/cosmos'
      preLoaderRoute: typeof CosmosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verified': {
      id: '/email-verified'
      path: '/email-verified'
      fullPath: '/email-verified'
      preLoaderRoute: typeof EmailVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/love-score': {
      id: '/love-score'
      path: '/love-score'
      fullPath: '/love-score'
      preLoaderRoute: typeof LoveScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-khoan': {
      id: '/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof TaiKhoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tao-y-tuong': {
      id: '/tao-y-tuong'
      path: '/tao-y-tuong'
      fullPath: '/tao-y-tuong'
      preLoaderRoute: typeof TaoYTuongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/your-turn': {
      id: '/your-turn'
      path: '/your-turn'
      fullPath: '/your-turn'
      preLoaderRoute: typeof YourTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fun-cosmos/tra-cuu': {
      id: '/fun-cosmos/tra-cuu'
      path: '/fun-cosmos/tra-cuu'
      fullPath: '/fun-cosmos/tra-cuu'
      preLoaderRoute: typeof FunCosmosTraCuuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fun-cosmos/rewards': {
      id: '/admin/fun-cosmos/rewards'
      path: '/admin/fun-cosmos/rewards'
      fullPath: '/admin/fun-cosmos/rewards'
      preLoaderRoute: typeof AdminFunCosmosRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fun-cosmos/submissions': {
      id: '/admin/fun-cosmos/submissions'
      path: '/admin/fun-cosmos/submissions'
      fullPath: '/admin/fun-cosmos/submissions'
      preLoaderRoute: typeof AdminFunCosmosSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reset-password': {
      id: '/api/public/reset-password'
      path: '/api/public/reset-password'
      fullPath: '/api/public/reset-password'
      preLoaderRoute: typeof ApiPublicResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AngelAiRoute: AngelAiRoute,
  CosmosRoute: CosmosRoute,
  EcosystemRoute: EcosystemRoute,
  EmailVerifiedRoute: EmailVerifiedRoute,
  LoveScoreRoute: LoveScoreRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TaiKhoanRoute: TaiKhoanRoute,
  TaoYTuongRoute: TaoYTuongRoute,
  YourTurnRoute: YourTurnRoute,
  AdminLoginRoute: AdminLoginRoute,
  FunCosmosTraCuuRoute: FunCosmosTraCuuRoute,
  AdminFunCosmosRewardsRoute: AdminFunCosmosRewardsRoute,
  AdminFunCosmosSubmissionsRoute: AdminFunCosmosSubmissionsRoute,
  ApiPublicResetPasswordRoute: ApiPublicResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
