/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AngelAiRouteImport } from './routes/angel-ai'
import { Route as CosmosRouteImport } from './routes/cosmos'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as EmailVerifiedRouteImport } from './routes/email-verified'
import { Route as LoveScoreRouteImport } from './routes/love-score'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as YourTurnRouteImport } from './routes/your-turn'
import { Route as ApiPublicResetPasswordRouteImport } from './routes/api/public/reset-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AngelAiRoute = AngelAiRouteImport.update({
  id: '/angel-ai',
  path: '/angel-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmosRoute = CosmosRouteImport.update({
  id: '/cosmos',
  path: '/cosmos',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifiedRoute = EmailVerifiedRouteImport.update({
  id: '/email-verified',
  path: '/email-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const LoveScoreRoute = LoveScoreRouteImport.update({
  id: '/love-score',
  path: '/love-score',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const YourTurnRoute = YourTurnRouteImport.update({
  id: '/your-turn',
  path: '/your-turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResetPasswordRoute = ApiPublicResetPasswordRouteImport.update({
  id: '/api/public/reset-password',
  path: '/api/public/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/angel-ai': typeof AngelAiRoute
  '/cosmos': typeof CosmosRoute
  '/ecosystem': typeof EcosystemRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/love-score': typeof LoveScoreRoute
  '/reset-password': typeof ResetPasswordRoute
  '/your-turn': typeof YourTurnRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/angel-ai': typeof AngelAiRoute
  '/cosmos': typeof CosmosRoute
  '/ecosystem': typeof EcosystemRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/love-score': typeof LoveScoreRoute
  '/reset-password': typeof ResetPasswordRoute
  '/your-turn': typeof YourTurnRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/angel-ai': typeof AngelAiRoute
  '/cosmos': typeof CosmosRoute
  '/ecosystem': typeof EcosystemRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/love-score': typeof LoveScoreRoute
  '/reset-password': typeof ResetPasswordRoute
  '/your-turn': typeof YourTurnRoute
  '/api/public/reset-password': typeof ApiPublicResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/angel-ai'
    | '/cosmos'
    | '/ecosystem'
    | '/email-verified'
    | '/love-score'
    | '/reset-password'
    | '/your-turn'
    | '/api/public/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/angel-ai'
    | '/cosmos'
    | '/ecosystem'
    | '/email-verified'
    | '/love-score'
    | '/reset-password'
    | '/your-turn'
    | '/api/public/reset-password'
  id:
    | '__root__'
    | '/'
    | '/angel-ai'
    | '/cosmos'
    | '/ecosystem'
    | '/email-verified'
    | '/love-score'
    | '/reset-password'
    | '/your-turn'
    | '/api/public/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AngelAiRoute: typeof AngelAiRoute
  CosmosRoute: typeof CosmosRoute
  EcosystemRoute: typeof EcosystemRoute
  EmailVerifiedRoute: typeof EmailVerifiedRoute
  LoveScoreRoute: typeof LoveScoreRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  YourTurnRoute: typeof YourTurnRoute
  ApiPublicResetPasswordRoute: typeof ApiPublicResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angel-ai': {
      id: '/angel-ai'
      path: '/angel-ai'
      fullPath: '/angel-ai'
      preLoaderRoute: typeof AngelAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmos': {
      id: '/cosmos'
      path: '/cosmos'
      fullPath: '/cosmos'
      preLoaderRoute: typeof CosmosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verified': {
      id: '/email-verified'
      path: '/email-verified'
      fullPath: '/email-verified'
      preLoaderRoute: typeof EmailVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/love-score': {
      id: '/love-score'
      path: '/love-score'
      fullPath: '/love-score'
      preLoaderRoute: typeof LoveScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/your-turn': {
      id: '/your-turn'
      path: '/your-turn'
      fullPath: '/your-turn'
      preLoaderRoute: typeof YourTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reset-password': {
      id: '/api/public/reset-password'
      path: '/api/public/reset-password'
      fullPath: '/api/public/reset-password'
      preLoaderRoute: typeof ApiPublicResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AngelAiRoute: AngelAiRoute,
  CosmosRoute: CosmosRoute,
  EcosystemRoute: EcosystemRoute,
  EmailVerifiedRoute: EmailVerifiedRoute,
  LoveScoreRoute: LoveScoreRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  YourTurnRoute: YourTurnRoute,
  ApiPublicResetPasswordRoute: ApiPublicResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
